# --- Étape 1 : Build ---
FROM node:22.14.0 AS builder

WORKDIR /app

COPY package*.json ./

# Installer toutes les dépendances pour builder l'app
RUN npm ci

COPY . .

# Construire l'application (ex: Next.js ou Tailwind build)
RUN npm run build

# --- Étape 2 : Image de production ---
FROM node:22.14.0 AS prod

WORKDIR /app

# Copier uniquement les fichiers nécessaires
COPY package*.json ./

# Installer seulement les dépendances de production
RUN npm ci --omit=dev

# Copier le build depuis l'étape builder
COPY --from=builder /app/.next ./.next    # si Next.js
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./

EXPOSE 3000

CMD ["npm", "start"]







#FROM node:22.14.0

#ENV HOST='0.0.0.0'
#ENV PORT='3000'

#WORKDIR /app

#COPY package*.json ./

#RUN npm ci

#COPY . .

#RUN npm run build

#EXPOSE 3000

#CMD [ "npm", "start" ]
