# ------------------------------
# Stage unique - Production
# ------------------------------
FROM node:20-alpine AS prod

# Définir le répertoire de travail
WORKDIR /app

# Copier seulement les fichiers nécessaires
COPY package*.json ./

# Installer uniquement les dépendances de production
RUN npm ci

# Copier le reste de l'application
COPY . .

# Construire l'application (Next.js ou autre)
RUN npm run build

# Exposer le port (si tu utilises Next.js standalone)
EXPOSE 3000

# Lancer l'application en mode production
CMD ["npm", "start"]






#FROM node:22.14.0

#ENV HOST='0.0.0.0'
#ENV PORT='3000'

#WORKDIR /app

#COPY package*.json ./

#RUN npm ci

#COPY . .

#RUN npm run build

#EXPOSE 3000

#CMD [ "npm", "start" ]
